'use client'

import { useEffect } from 'react'

/**
 * Registers the service worker generated by scripts/generate-service-worker.mjs.
 *
 * Skipped outside production: `next dev` has no `out/sw.js` (it's a build-time
 * artefact), and a dev-mode registration would just cache hot-reloaded output
 * and get in the way.
 */
export function RegisterServiceWorker() {
  useEffect(() => {
    if (process.env.NODE_ENV !== 'production') return
    if (!('serviceWorker' in navigator)) return

    const basePath = process.env.NEXT_PUBLIC_BASE_PATH || ''
    navigator.serviceWorker.register(`${basePath}/sw.js`).catch(() => {
      // Offline install/update isn't essential to using the site — fail quietly.
    })
  }, [])

  return null
}
